//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMo.SQLDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int BalanceId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<System.DateTime> BalanceDueDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
